apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bifrost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bifrost.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: bifrost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "bifrost.fullname" . }}-data
