apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-pipeline-sa
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-pipeline-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "ci-pipeline-sa"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-pipeline-admin-binding
subjects:
- kind: ServiceAccount
  name: ci-pipeline-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io


