{{- $pg := lookup "v1" "Secret" .Values.postgresql.namespace "postgresql" }}
{{- $pg_password := "placeholder-password" }}
{{- if and $pg $pg.data }}
  {{- $pg_password = index $pg.data "password" | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  url: >-
    postgres://{{ .Values.postgresql.auth.username }}:{{ $pg_password }}@postgresql.{{ .Values.postgresql.namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable
