apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "h2o.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2o.labels" . | nindent 4 }}
spec:
  secretName: {{ include "h2o.fullname" . }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.i.wingu.se"
