{{- if .Values.ingress.enabled -}}
{{- $fullName := include "browser.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "browser.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.fas.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s@kubernetescrd" .Values.fas.namespace .Values.fas.middlewareName | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain | quote }}
      secretName: {{ .Values.tls.commonSecretName | quote }}
  rules:
    - host: {{ .Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
