replicaCount: 1

image:
  registry: ghcr.io
  repository: winguse/browser
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  domain: s.o.wingu.se
  annotations: {}

tls:
  commonSecretName: "common-tls"

fas:
  enabled: true
  namespace: "fas"
  middlewareName: "fas-auth"

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi
