replicaCount: 1

image:
  registry: ghcr.io
  repository: winguse/browser
  tag: "v0.0.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  domain: s.i.wingu.se
  annotations: {}

tls:
  commonSecretName: "common-tls"

fas:
  enabled: true
  namespace: "fas"
  middlewareName: "fas-auth"

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

networkPolicy:
  enabled: true
  ingressFrom:
    - namespaceLabels:
        kubernetes.io/metadata.name: kube-system
      podLabels:
        app.kubernetes.io/name: envoy
    - namespaceLabels:
        kubernetes.io/metadata.name: kube-system
      podLabels:
        app.kubernetes.io/name: traefik
  dnsNamespaceLabels:
    kubernetes.io/metadata.name: kube-system
  privateCidrsExcept:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 100.64.0.0/10
    - 169.254.0.0/16
