{{- if .Values.ingress.enabled -}}
{{- $fullName := include "litellm.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: envoy
      namespace: gw
  {{- if .Values.ingress.hosts }}
  hostnames:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
{{- end }}
