apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
  LITELLM_MASTER_KEY: {{ .Values.masterKey | quote }}
