{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hermes-agent.fullname" . -}}
{{- $svcPortDashboard := .Values.service.dashboardPort | default 3000 -}}
{{- $svcPortApi := .Values.service.apiPort | default 8000 -}}
{{- $svcPortCodeServer := .Values.service.codeServerPort | default 8080 -}}
{{- range .Values.ingress.hosts -}}
{{- $host := .host -}}
{{- $paths := .paths -}}
{{- $isCodeServer := false -}}
{{- range $paths }}{{ if eq .portType "code-server" }}{{ $isCodeServer = true }}{{ end }}{{ end -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}{{ if $isCodeServer }}-codeserver{{ else }}-dashboard{{ end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "hermes-agent.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: envoy
      namespace: gw
      sectionName: {{ if $isCodeServer }}https-mtls-hmc{{ else }}https-mtls-hm{{ end }}
  hostnames:
    - {{ $host | quote }}
  rules:
    {{- range $paths }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ if eq .portType "api" }}{{ $svcPortApi }}{{ else if eq .portType "code-server" }}{{ $svcPortCodeServer }}{{ else }}{{ $svcPortDashboard }}{{ end }}
    {{- end }}
---
{{- end -}}
{{- end -}}
