{{- if and (not .Values.existingSecret) .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-agent.fullname" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{- if not (eq $val "") }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
