apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-agent.fullname" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
    {{- if .Values.codeServer.enabled }}
    - port: {{ .Values.service.codeServerPort | default 8080 }}
      targetPort: code-server
      protocol: TCP
      name: code-server
    {{- end }}
  selector:
    {{- include "hermes-agent.selectorLabels" . | nindent 4 }}
