apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-mtls-a
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
      sectionName: https-mtls-a
  tls:
    clientValidation:
      caCertificateRefs:
        - name: mtls-ca-bundle
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-mtls-hm
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
      sectionName: https-mtls-hm
  tls:
    clientValidation:
      caCertificateRefs:
        - name: mtls-ca-bundle
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-mtls-hmc
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
      sectionName: https-mtls-hmc
  tls:
    clientValidation:
      caCertificateRefs:
        - name: mtls-ca-bundle
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-mtls-omni
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
      sectionName: https-mtls-omni
  tls:
    clientValidation:
      caCertificateRefs:
        - name: mtls-ca-bundle
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-mtls-oc
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
      sectionName: https-mtls-oc
  tls:
    clientValidation:
      caCertificateRefs:
        - name: mtls-ca-bundle
---
apiVersion: v1
kind: Secret
metadata:
  name: mtls-ca-bundle
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.ca: {{ printf "%s\n%s" (.Files.Get "certs/mtlsca.crt") (.Files.Get "certs/mtlsca-095.crt") | b64enc | quote }}
