{{- if .Values.tlsAnchor.enabled -}}
{{- $dummyHost := printf "tls-anchor.%s" .Values.tls.commonWildcardDomain | replace "*." "" -}}
apiVersion: v1
kind: Service
metadata:
  name: tls-anchor
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: localhost
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-anchor
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.tlsAnchor.ingressClassName | default "traefik" }}
  tls:
    - hosts:
        - {{ .Values.tls.commonWildcardDomain | quote }}
      secretName: {{ .Values.tls.commonSecretName }}
    - hosts:
        - {{ .Values.tls.coderWildcardDomain | quote }}
      secretName: {{ .Values.tls.coderSecretName | default "coder-tls" }}
  rules:
    - host: {{ $dummyHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tls-anchor
                port:
                  number: 80
{{- end }}
