service:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
  spec:
    externalTrafficPolicy: Local
    healthCheckNodePort: 30122
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
