# Helm values for Metrics Server
image:
  repository: registry.k8s.io/metrics-server/metrics-server

args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
