ports:
  web:
    nodePort: 31080
    forwardedHeaders:
      trustedIPs: &trusted_ips
        - "127.0.0.1/32"
        - "10.0.0.0/8"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    nodePort: 31332
    forwardedHeaders:
      trustedIPs: *trusted_ips

# this only for OKE (Oracle Cloud Kubernetes Service)
service:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
  spec:
    externalTrafficPolicy: Local
    healthCheckNodePort: 30122
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
