apiVersion: v1
kind: Service
metadata:
  name: {{ include "omniroute.fullname" . }}
  labels:
    {{- include "omniroute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.liveWsPort }}
      targetPort: live-ws
      protocol: TCP
      name: live-ws
  selector:
    {{- include "omniroute.selectorLabels" . | nindent 4 }}
