replicaCount: 1

image:
  registry: ghcr.io
  repository: winguse/fas
  tag: "0.0.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  domain: a.o.wingu.se
  annotations: {}

tls:
  commonSecretName: "common-tls"

mtls:
  enabled: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "micro-nfs"
  mountPath: /data

env:
  FAS_PORT: "8080"
  FAS_DATA_FILE: "/data/fas.jsonl"
  FAS_ACL_FILE: "/data/acl.yaml"

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

networkPolicy:
  enabled: true
  ingressLabels:
    app.kubernetes.io/name: traefik
  ingressNamespaceLabels:
    kubernetes.io/metadata.name: kube-system
