apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "fas.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fas.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewayName | default "envoy" }}
  extAuth:
    http:
      path: /_auth
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "fas.fullname" . }}
          port: {{ int .Values.service.port }}
