apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "fas.fullname" . }}-reference-grant
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fas.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: browser
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: hermes-playground
  to:
    - group: ""
      kind: Service
      name: {{ include "fas.fullname" . }}
