{{- if .Values.sharedSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fas.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fas.labels" . | nindent 4 }}
type: Opaque
stringData:
  FAS_SHARED_SECRET: {{ .Values.sharedSecret | quote }}
{{- end }}
