replicaCount: 1

image:
  repository: docker.io/maximhq/bifrost
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  hosts: []
  tls: []

publicIngress:
  enabled: false
  className: traefik
  hosts: []
  tls: []

mtls:
  enabled: false

persistence:
  enabled: true
  size: 10Gi
  storageClass: "micro-nfs"

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
